export const lightColors = {
  surface: '#f4fbf4',
  surfaceDim: '#d4dcd5',
  surfaceBright: '#f4fbf4',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#eef6ee',
  surfaceContainer: '#e8f0e9',
  surfaceContainerHigh: '#e3eae3',
  surfaceContainerHighest: '#dde4dd',
  onSurface: '#161d19',
  onSurfaceVariant: '#3c4a42',
  inverseSurface: '#2b322d',
  inverseOnSurface: '#ebf3eb',
  outline: '#6c7a71',
  outlineVariant: '#bbcabf',
  surfaceTint: '#006c49',
  primary: '#006c49',
  onPrimary: '#ffffff',
  primaryContainer: '#10b981',
  onPrimaryContainer: '#00422b',
  inversePrimary: '#4edea3',
  secondary: '#855300',
  onSecondary: '#ffffff',
  secondaryContainer: '#F59E0B', // Artisanal Gold
  onSecondaryContainer: '#064E3B', // Deep Forest
  tertiary: '#a43a3a',
  onTertiary: '#ffffff',
  tertiaryContainer: '#fc7c78',
  onTertiaryContainer: '#711419',
  error: '#ba1a1a',
  onEerror: '#ffffff',
  errorContainer: '#ffdad6',
  onEerrorContainer: '#93000a',
  primaryFixed: '#6ffbbe',
  primaryFixedDim: '#4edea3',
  onPrimaryFixed: '#002113',
  onPrimaryFixedVariant: '#005236',
  secondaryFixed: '#ffddb8',
  secondaryFixedDim: '#ffb95f',
  onSecondaryFixed: '#2a1700',
  onSecondaryFixedVariant: '#653e00',
  tertiaryFixed: '#ffdad7',
  tertiaryFixedDim: '#ffb3af',
  onTertiaryFixed: '#410005',
  onTertiaryFixedVariant: '#842225',
  background: '#f4fbf4',
  onBackground: '#161d19',
  surfaceVariant: '#dde4dd',
  shadow: '#10B98126', // Tinted emerald shadow (15% opacity)
};
